Set juliacall env vars for quarto-preview as well
Doing this in a fresh clone caused the root Project.toml to be overwritten; see also issue https://github.com/JuliaPy/pyjuliapkg/issues/62.

That lead to errors like:

```
JuliaError: ArgumentError: Package Ribasim not found in current path.
```