Add ipykernel to pixi deps (#1542)
Not sure if manifest version 5 will cause trouble.

I use VS Code for interactive development, which requires ipykernel.
Since VS Code uses the pixi env, I always end up adding ipykernel in the
past months. Seems like a good developer addition.

Similarly, I always limit the pyarrow version, as I otherwise get a 
```python
  File "/Users/evetion/code/Ribasim.jl/.pixi/envs/dev/lib/python3.12/site-packages/pandas/compat/pyarrow.py", line 10, in <module>
    _palv = Version(Version(pa.__version__).base_version)
                            ^^^^^^^^^^^^^^
AttributeError: module 'pyarrow' has no attribute '__version__'
```

I'm not sure why the CI doesn't reproduce this.

---------

Co-authored-by: Martijn Visser <mgvisser@gmail.com>