Update Julia Manifest.toml (#2751)
Like https://github.com/Deltares/Ribasim/pull/2713 but keeping (and
pinning) LinearSolve at v3.46.1. More recent releases give this error
when running the basic model:

```
ERROR: type Nothing has no field colptr
Stacktrace:
  [1] getproperty
    @ .\Base.jl:49 [inlined]
  [2] pattern_changed(fact::Nothing, A::SparseArrays.SparseMatrixCSC{Float64, Int64})
    @ LinearSolveSparseArraysExt C:\ProgramData\DevDrives\.julia\packages\LinearSolve\ki2KA\ext\LinearSolveSparseArraysExt.jl:397
  [3] solve!(cache::LinearSolve.LinearCache{OrdinaryDiffEqDifferentiation.WOperator{true, Float64, LinearAlgebra.UniformScaling{Bool}, Float64, SciMLOperators.MatrixOperator{Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}, SciMLOperators.FilterKwargs{Nothing, Val{()}}, SciMLOperators.FilterKwargs{Returns{Nothing}, Val{()}}}, Ribasim.CArrays.CArray{Float64, 1, Vector{Float64}, @NamedTuple{combined_cumulative_flows::
UnitRange{Int64}, integral::UnitRange{Int64}}}, SparseArrays.SparseMatrixCSC{Float64, Int64}, Nothing}, Ribasim.CArrays.CArray{Float64, 1, Vector{Float64}, @NamedTuple{combined_cumulative_flows::UnitRange{Int64},
 integral::UnitRange{Int64}}}, Vector{Float64}, SciMLBase.NullParameters, LinearSolve.KLUFactorization, Nothing, LinearSolve.InvPreconditioner{LinearAlgebra.Diagonal{Float64, Ribasim.CArrays.CArray{Float64, 1, Ve
ctor{Float64}, @NamedTuple{tabulated_rating_curve::UnitRange{Int64}, pump::UnitRange{Int64}, outlet::UnitRange{Int64}, user_demand_inflow::UnitRange{Int64}, user_demand_outflow::UnitRange{Int64}, linear_resistanc
e::UnitRange{Int64}, manning_resistance::UnitRange{Int64}, evaporation::UnitRange{Int64}, infiltration::UnitRange{Int64}, integral::UnitRange{Int64}}}}}, LinearAlgebra.Diagonal{Float64, Ribasim.CArrays.CArray{Flo
at64, 1, Vector{Float64}, @NamedTuple{tabulated_rating_curve::UnitRange{Int64}, pump::UnitRange{Int64}, outlet::UnitRange{Int64}, user_demand_inflow::UnitRange{Int64}, user_demand_outflow::UnitRange{Int64}, linea
r_resistance::UnitRange{Int64}, manning_resistance::UnitRange{Int64}, evaporation::UnitRange{Int64}, infiltration::UnitRange{Int64}, integral::UnitRange{Int64}}}}, Float64, LinearSolve.LinearVerbosity{SciMLLoggin
g.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.CustomLevel, SciMLLogging.Silent, SciMLLogging.InfoLevel, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel,
 SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel}, Bool, LinearSolve.LinearSolveAdjoint{Missing}}, alg::LinearSolve.KLUFactori
zation; kwargs::@Kwargs{reltol::Vector{Float64}})
    @ LinearSolveSparseArraysExt C:\ProgramData\DevDrives\.julia\packages\LinearSolve\ki2KA\ext\LinearSolveSparseArraysExt.jl:283
  [4] solve!(::LinearSolve.LinearCache{OrdinaryDiffEqDifferentiation.WOperator{true, Float64, LinearAlgebra.UniformScaling{Bool}, Float64, SciMLOperators.MatrixOperator{Float64, SparseArrays.SparseMatrixCSC{Float
64, Int64}, SciMLOperators.FilterKwargs{Nothing, Val{()}}, SciMLOperators.FilterKwargs{Returns{Nothing}, Val{()}}}, Ribasim.CArrays.CArray{Float64, 1, Vector{Float64}, @NamedTuple{combined_cumulative_flows::UnitR
ange{Int64}, integral::UnitRange{Int64}}}, SparseArrays.SparseMatrixCSC{Float64, Int64}, Nothing}, Ribasim.CArrays.CArray{Float64, 1, Vector{Float64}, @NamedTuple{combined_cumulative_flows::UnitRange{Int64}, inte
gral::UnitRange{Int64}}}, Vector{Float64}, SciMLBase.NullParameters, LinearSolve.KLUFactorization, Nothing, LinearSolve.InvPreconditioner{LinearAlgebra.Diagonal{Float64, Ribasim.CArrays.CArray{Float64, 1, Vector{
Float64}, @NamedTuple{tabulated_rating_curve::UnitRange{Int64}, pump::UnitRange{Int64}, outlet::UnitRange{Int64}, user_demand_inflow::UnitRange{Int64}, user_demand_outflow::UnitRange{Int64}, linear_resistance::Un
itRange{Int64}, manning_resistance::UnitRange{Int64}, evaporation::UnitRange{Int64}, infiltration::UnitRange{Int64}, integral::UnitRange{Int64}}}}}, LinearAlgebra.Diagonal{Float64, Ribasim.CArrays.CArray{Float64,
 1, Vector{Float64}, @NamedTuple{tabulated_rating_curve::UnitRange{Int64}, pump::UnitRange{Int64}, outlet::UnitRange{Int64}, user_demand_inflow::UnitRange{Int64}, user_demand_outflow::UnitRange{Int64}, linear_res
istance::UnitRange{Int64}, manning_resistance::UnitRange{Int64}, evaporation::UnitRange{Int64}, infiltration::UnitRange{Int64}, integral::UnitRange{Int64}}}}, Float64, LinearSolve.LinearVerbosity{SciMLLogging.Sil
ent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.CustomLevel, SciMLLogging.Silent, SciMLLogging.InfoLevel, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel, SciM
LLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel}, Bool, LinearSolve.LinearSolveAdjoint{Missing}}; kwargs::@Kwargs{reltol::Vector{F
loat64}})
    @ LinearSolve C:\ProgramData\DevDrives\.julia\packages\LinearSolve\ki2KA\src\common.jl:441
```

It seems that something in
https://github.com/SciML/LinearSolve.jl/releases/tag/v3.47.0 broke it.
https://github.com/SciML/LinearSolve.jl/compare/v3.46.1...v3.47.0

This also switches TestItemRunner back to a release now that
https://github.com/julia-vscode/TestItemRunner.jl/pull/109 is released.