fix pixi to v0.7.0 in GitHub Actions (#837)
V0.8.0 just came out and now our CI is broken. Let's try if this fixes
it so we can upgrade at a better time.

https://github.com/prefix-dev/pixi/releases/tag/v0.8.0

The CI error is this for the Julia tests:

```
✨ Pixi task: python utils/generate-testmodels.py
Traceback (most recent call last):
  File "/home/runner/work/Ribasim/Ribasim/utils/generate-testmodels.py", line 4, in <module>
    import ribasim_testmodels
ModuleNotFoundError: No module named 'ribasim_testmodels'
Error: Process completed with exit code 1.
```

And this for the docs:

```
✨ Pixi task: quartodoc build && rm objects.json
Traceback (most recent call last):
  File "/home/runner/work/Ribasim/Ribasim/.pixi/env/lib/python3.11/site-packages/griffe/loader.py", line 114, in load_module
    module_name, package = self.finder.find_spec(module, try_relative_path=try_relative_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/Ribasim/Ribasim/.pixi/env/lib/python3.11/site-packages/griffe/finder.py", line 130, in find_spec
    return module_name, self.find_package(top_module_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/Ribasim/Ribasim/.pixi/env/lib/python3.11/site-packages/griffe/finder.py", line 16[9](https://github.com/Deltares/Ribasim/actions/runs/7008476409/job/19064863939?pr=836#step:8:10), in find_package
    raise ModuleNotFoundError(module_name)
ModuleNotFoundError: ribasim
```