Use older runic pre-commit hook (#2825)
I see that the current version is failing half the time, saying that the
project is not instantiated. The v2 hook relies on pre-commit julia
support, which is possibly buggy. The v1 hook doesn't, let's try that.

Also updates the python version to run the hooks to 3.13 like our dev
env, and remove the Runic version, we can always do so later if that
becomes an issue.

Issue observed:
```
check runic formatting...................................................Failed
- hook id: runic
- exit code: 1

ERROR: LoadError: ArgumentError: Package Runic [62bfec6d-59d7-401d-8490-b29ee721c001] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] __require_prelocked(pkg::Base.PkgId, env::String)
   @ Base ./loading.jl:2615
 [2] _require_prelocked(uuidkey::Base.PkgId, env::String)
   @ Base ./loading.jl:2493
 [3] macro expansion
   @ ./loading.jl:2421 [inlined]
 [4] macro expansion
   @ ./lock.jl:376 [inlined]
 [5] __require(into::Module, mod::Symbol)
   @ Base ./loading.jl:2386
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:2362
 [7] include(mod::Module, _path::String)
   @ Base ./Base.jl:306
 [8] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:317
 [9] _start()
   @ Base ./client.jl:550
in expression starting at /home/runner/.cache/pre-commit/repofn616frs/src/runic.jl:3
ERROR: LoadError: ArgumentError: Package Runic [62bfec6d-59d7-401d-8490-b29ee721c001] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
```