Add `pixi run ribasim-models` to run all test models (#1224)
This runs them all in a single Julia session to avoid latency. I didn't
add this to CI for now since we already run them all on TeamCity using
the CLI. But this is especially helpful during development to see which
models fail and why.

If I intentionally break two models you see this output at the end:

```
[ Info: Ran 32 models, 30 passed, 2 failed.
Failed models:
bucket
rating_curve
```

And in between the normal output:
```
[ Info: Running model bucket
ERROR: expect key: starttime
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] macro expansion
    @ C:\Users\visser_mn\.julia\packages\Configurations\Yxczn\src\from_dict.jl:0 [inlined]
  [3] from_dict_specialize(::Type{Ribasim.config.Toml}, d::Dict{String, Any})
    @ Ribasim.config C:\Users\visser_mn\.julia\packages\Configurations\Yxczn\src\codegen.jl:362
  [4] #from_dict#4
    @ C:\Users\visser_mn\.julia\packages\Configurations\Yxczn\src\from_dict.jl:46 [inlined]
  [5] from_dict
    @ C:\Users\visser_mn\.julia\packages\Configurations\Yxczn\src\from_dict.jl:33 [inlined]
  [6] from_toml(::Type{Ribasim.config.Toml}, filename::String; kw::@Kwargs{})
    @ Configurations C:\Users\visser_mn\.julia\packages\Configurations\Yxczn\src\from_toml.jl:18
  [7] from_toml
    @ C:\Users\visser_mn\.julia\packages\Configurations\Yxczn\src\from_toml.jl:8 [inlined]
  [8] #Config#62
    @ D:\Ribasim\core\src\config.jl:147 [inlined]
  [9] Config
    @ D:\Ribasim\core\src\config.jl:146 [inlined]
┌ Error: Simulation failed
│   modelname = "bucket"
└ @ Main D:\Ribasim\utils\testmodelrun.jl:15
```

---------

Co-authored-by: Hofer-Julian <julianhofer@gnome.org>