Don't set external filepath in TOML `if df is None` (#3214)
If I have a model with this external file:

```toml
[basin]
time = "basin_time.nc"
```

And I then remove that table in Python:

```python
model.basin.time.df = None
```

It will leave the reference in the TOML, but not write the NetCDF file.
That crashes the core with:

```
ERROR: NetCDF error: Opening path input/basin_time.nc: No such file or directory (NetCDF error code: 2)
```

What I want is to remove the TOML reference when I clear the table in
Python.

Ran into this in Ribasim-NL.