Create MSIX app package (#2710)
Fixes https://github.com/Deltares/Ribasim/issues/2686.
This follows the Microsoft guide from
https://learn.microsoft.com/en-us/windows/msix/package/manual-packaging-root

<img width="652" height="444" alt="image"
src="https://github.com/user-attachments/assets/2874a00f-8aab-4223-a24a-33048e9af6e9"
/>

It automatically puts `ribasim.exe` on the path at
`C:\Users\visser_mn\AppData\Local\Microsoft\WindowsApps\ribasim.exe` via
the recommended `AppExecutionAlias` mechanism.

The
[capabilities](https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-manual-conversion#capabilities)
are on `runFullTrust`. I looked a bit into this but makeappx.exe states
that for this package manifest this is required.

The "Launch when ready" toggle cannot be controlled by the manifest. If
left checked you'll just see a quick flash of a terminal which then
closes, as you'd expect when running ribasim.exe without arguments.

Uninstallation is automatically available:

<img width="468" height="354" alt="image"
src="https://github.com/user-attachments/assets/2c290d29-94ee-4fe7-b64b-e9f0240b7c35"
/>

This still needs to be hooked up to TeamCity's code signing. The MSIX
can only be used when signed. To test I signed it with a self-signed
certificate, but that doesn't work on other computers. I provide some
PowerShell commands here that can be used to create the
`ribasim_windows.msix` under the `/build/` directory.

```ps1
# Add Windows SDK to PATH for this session
$env:Path += ";C:\Program Files (x86)\Windows Kits\10\App Certification Kit"
# Versioned path: c:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\

# copy files needed for MSIX to the build directory
# we could also check them in there, but I'd rather not have these files in the .zip artifacts
# we could also supply a mapping file with `/f` instead of the directory argument `/d` to `makeappx`
# but that would require us to maintain the mapping file with currently over 1k files
Copy-Item AppxManifest.xml ribasim/
Copy-Item logo-150.png ribasim/
Copy-Item logo-44.png ribasim/

# pack the directory ribasim to ribasim_windows.msix, overwriting existing msix files
makeappx pack /o /d ribasim /p ribasim_windows.msix

# probably best to use existing signing TeamCity scripts as a template
SignTool sign /fd SHA256 /sha1 <cert_sha> ribasim_windows.msix
```

This puts ribasim.exe on the path, but not the bin dir with all DLLs and
libribasim.dll. For libribasim users it is probably a better idea to
keep using the zip install.

EDIT: whilst `ribasim --version` works fine, running a model doesn't, it
cannot find libribasim:

```
❯ ribasim ribasim.toml

thread 'main' panicked at src\main.rs:63:49:
called `Result::unwrap()` on an `Err` value: LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is related to there being limited file permissions in the
installation directory under WindowsApps.
One way to avoid this is to put ribasim.exe in the bin dir with all the
libraries.
We still need to see if we can avoid TimeZones.jl writing to
scratchspaces in this restricted dir:

<details><summary>Scratchspaces</summary>
<p>

```
InitError(mod=:TZData, error=Base.IOError(msg="mkdir(\"C:\\\\Program Files\\\\WindowsApps\\\\Deltares.Ribasim_2025.6.0.0_x64__m018s8shtq18w\\\\share\\\\julia\\\\scratchspaces\"; mode=0o777): permission denied (EACCES)", code=Int32(-4092)))
uv_error at .\libuv.jl:106 [inlined]
#mkdir#8 at .\file.jl:185
mkdir at .\file.jl:177 [inlined]
#mkpath#9 at .\file.jl:241
mkpath at .\file.jl:235
#mkpath#9 at .\file.jl:239
mkpath at .\file.jl:235
#mkpath#9 at .\file.jl:239
mkpath at .\file.jl:235 [inlined]
#get_scratch!#10 at D:\buildAgent\work\ecd2b8f9b25b1609\.julia\packages\Scratch\tDtSY\src\Scratch.jl:245
get_scratch! at D:\buildAgent\work\ecd2b8f9b25b1609\.julia\packages\Scratch\tDtSY\src\Scratch.jl:230 [inlined]
macro expansion at D:\buildAgent\work\ecd2b8f9b25b1609\.julia\packages\Scratch\tDtSY\src\Scratch.jl:315 [inlined]
_scratch_dir at D:\buildAgent\work\ecd2b8f9b25b1609\.julia\packages\TimeZones\dt27j\src\TimeZones.jl:35
__init__ at D:\buildAgent\work\ecd2b8f9b25b1609\.julia\packages\TimeZones\dt27j\src\tzdata\TZData.jl:19
jfptr___init___195813.1 at C:\Program Files\WindowsApps\Deltares.Ribasim_2025.6.0.0_x64__m018s8shtq18w\bin\libribasim.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_module_run_initializer at C:/workdir/src\toplevel.c:76
_finish_julia_init at C:/workdir/src\init.c:902
```

</p>
</details> 

We can look into using Preferences.jl to avoid writing here. That
doesn't seem directly supported though. It seems that I have
`scratchspaces\f269a46b-ccf7-5d73-abea-4c690281aa53\build\`, so perhaps
it is only writing an empty directory? Alternatively, we can look into
making the scratchspaces folder writable, see
https://learn.microsoft.com/en-us/windows/msix/psf/psf-filesystem-writepermission
EDIT: fixed by https://github.com/Deltares/Ribasim/pull/2738

If that works, we can also look if it is possible to specify
`libribasim.dll` in the AppxManifest.xml as a product, and see if other
apps (BMI) can then use that. EDIT: no this is not possible

---------

Co-authored-by: Maarten Pronk <git@evetion.nl>