Add pixi task to update registry (#962)
With our current workflow, it can happen that dev A updates the packages
in Manifest.toml, and dev B gets the error:

```
ERROR: Unsatisfiable requirements detected for package X
```

The problem is that dev B's local registry is outdated, so it is not
aware of the new versions of X that are being used. This adds a task to
update the registry, and runs it by default when building or installing.
That should make this error more rare, and perhaps easier to resolve.

Note that this is an issue that may get resolved in Pkg in the future;
https://github.com/JuliaLang/Pkg.jl/issues/3713